---
# tasks file for ansible-role-bes-sonarQube

- include: "tasks/oah-install.yml"
  when: oah_command == "install"

- include: "tasks/oah-remove.yml"
  when: oah_command == "remove"

- include: "tasks/oah-validate.yml"
  when: oah_command == "validate"

- include: "tasks/oah-update.yml"
  when: oah_command == "update"

- include: "tasks/oah-reset.yml"
  when: oah_command == "reset"

