---
# tasks file for ansible-role-bes-sonarQube

- include: "tasks/oah_install.yml"
  when: oah_command == "install"

- include: "tasks/oah_remove.yml"
  when: oah_command == "uninstall"

- include: "tasks/oah_validate.yml"
  when: oah_command == "validate"

- include: "tasks/oah_update.yml"
  when: oah_command == "update"

