---

- name: Checking the installed version
  shell: 'ls /opt/ | grep sonar | grep -Eo "([0-9]|\.)*(?=\s|$)"'
  register: sonar_installed_version

- name: Validating Sonarqube installation
  stat:
    path: "/opt/sonarqube-{{sonar_installed_version.stdout}}"
  register: sonarqube_installation

- name: If Sonarqube exists
  debug:
    msg: "Sonarqube is installed"
  when: "{{sonarqube_installation.stat.exists}}"

- name: Sonarqube not installed
  debug:
    msg: "Sonaqube not installed"
  when: not "{{sonarqube_installation.stat.exists}}"
